# Generated by Django 5.1.7 on 2025-03-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_task_taskgroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date'], 'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('due_date', 'name')},
        ),
    ]
